services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - forgejo-net  

  forgejo:
    build: ./forgejo
    container_name: forgejo-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - forgejo-data:/data
    networks:
      - forgejo-net

  nginx:
    build: ./nginx
    container_name: forgejo-nginx
    ports:
      - "80:80"
    depends_on:
      - forgejo
    networks:
      - forgejo-net

volumes:
  db-data:
  forgejo-data:

networks:
  forgejo-net:
